### ISSUE TITLE
Maven fail while importing apex app

### ISSUE THREAD

**Issue by Zdro** [nbuytaert1/orclapex-maven-plugin#3]
On ubuntu 12.04, the build fail with the following error :

[INFO] ...application deployment
[INFO] ...application install scripts
[INFO] ...application deployment checks
[INFO] ...application deployment build options
[INFO] ...post import process
[INFO] ...done
[INFO] Deconnecte de Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
[INFO] With the Partitioning, Real Application Clusters, Automatic Storage Management, OLAP,
[INFO] Advanced Analytics and Real Application Testing options
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 47.412 s
[INFO] Finished at: 2015-12-23T11:13:19+01:00
[INFO] Final Memory: 22M/183M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.contribute:orclapex-maven-plugin:1.0.1:import (app-import) on project orclapex-maven-demo-multi-env: Execution app-import of goal com.contribute:orclapex-maven-plugin:1.0.1:import failed: process hasn't exited -> [Help 1]

**Comment by nbuytaert1** [comment]
Thanks for the bug notification and merge request, and sorry for the super long delay.
